Adding hoprd metrics and Cadvisor
Rpc-h/applications-platform pull request #61
Opened 2023-07-17 16:36 UTC by ausias-armesto

Improving the monitoring of hoprd nodes done in https://github.com/Rpc-h/applications-platform/pull/60
Now we add monitoring of Cadvisor and hoprd metrics

2023-07-18 11:45 UTC, ausias-armesto commented on day-1/argocd.tf
> +# resource "kubernetes_resource_quota" "argocd" {
I commented out because there was an error. Here you can see it: https://github.com/Rpc-h/applications-platform/actions/runs/5586925058/jobs/10211576674
I didn't know how to solve it

2023-07-18 11:57 UTC, ausias-armesto commented on day-1/argocd.tf
> +# resource "kubernetes_resource_quota" "argocd" {
I prefer to leave it commented and when you are back you can solve it with a new PR

2023-07-19 07:25 UTC, esterlus requested changes
Can you rebase to latest main branch? All those nix related changes are already part of that branch.

2023-07-19 08:20 UTC, esterlus approved these changes
thanks

2023-07-19 21:48 UTC, Teebor-Choka approved these changes

2023-07-19 21:48 UTC, Teebor-Choka commented on .github/workflows/day-1-apply.yaml
> +          export $(cat .env | xargs)
Nice trick, will remember this.

2023-07-19 21:48 UTC, Teebor-Choka commented on day-1/argocd.tf
> +# resource "kubernetes_resource_quota" "argocd" {
Why?

2023-07-24 16:41 UTC, ausias-armesto commented on day-2/monitoring/kube-prometheus-stack/sealed-secrets/prometheus-scrape-config.yaml.j2
> +##
This file is used as a template to generate the desired sealed secret.
In the first lines are the instructions to generate it
https://github.com/Rpc-h/applications-platform/blob/1bccbcf8fde0774d57b567f82b73ff8ebaeb15be/day-2/monitoring/kube-prometheus-stack/sealed-secrets/prometheus-scrape-config.yaml.j2#L5

2023-07-24 16:42 UTC, ausias-armesto commented on day-1/argocd.tf
> +# resource "kubernetes_resource_quota" "argocd" {
I replied in a previous comment, didn't work and decided to comment temporary

2023-07-25 07:02 UTC, ausias-armesto commented on day-2/monitoring/kube-prometheus-stack/sealed-secrets/prometheus-scrape-config.yaml.j2
> +##
The reason is that the scrape config is too large because it contains 50 nodes, so I decided that it was a better idea to externalise it into a separated file. In this case, I chose a Secret instead of a ConfigMap because the scrape configuration requires of the sensitive data of the HOPR_API_TOKEN. This file is the template source to generate the sealed secret, which eventually will generate the Secret needed by Prometheus in this property https://github.com/Rpc-h/applications-platform/pull/61/files#diff-c8e4144b0e60949fdce0153ad8a7c303842b5455af81c3acccf7bf4f4775c9ebR116 . In the first lines of the file is documented how to use it. Basically you need to execute the command explained and the sealed secret will be generated.
```
sed 's#__SCRAPE_USERNAME__#'"$HOPRD_API_TOKEN"'#g' ./day-2/monitoring/kube-prometheus-stack/sealed-secrets/prometheus-scrape-config.yaml.j2 | kubeseal --controller-name=sealed-secrets --controller-namespace=sealed-secrets --format yaml > ./day-2/monitoring/kube-prometheus-stack/sealed-secrets/prometheus-scrape-config.yaml 
```

2023-07-25 19:25 UTC, ausias-armesto commented on day-2/monitoring/kube-prometheus-stack/sealed-secrets/prometheus-scrape-config.yaml.j2
> +##
I don't understand your question, neither your doubt, sorry. 
I needed is to set the manual scrape configuration in an encrypted way. I didn't find any other option to do it unless we use the same style than in Core Team, where applications are custom helm charts with a dependency with the base helm chart that is customising.

2023-07-28 07:11 UTC, merged